#!/bin/bash

# Encode from argument or from STDIN
[ -z "$1" ] && VAL="$(cat /dev/stdin)" || VAL="$1"

# Base64 encode plus URL encoding
echo -n "$VAL" \
  | tr -d '[:space:]' \
  | openssl base64 -e -A \
  | tr '+/' '-_' \
  | tr -d =
