#!/bin/bash

source deployees

usage() {
  cat <<EOF
deploy provides easy deployment to Firefox Addons and the Chrome Webstore.

Usage: deploy command [options] file.zip

Commands:
  firefox   deploy to Firefox Addons
  chrome    deploy to Chrome Webstore
  help      display this help text
EOF
}

VERSION=$(git tag -l | tail -1 | sed s/v//)

case $1 in
  firefox)
    shift
    firefox $@
    ;;
  chrome)
    shift
    chrome $@
    ;;
  help)
    usage
    ;;
  *)
    usage
    exit 1
    ;;
esac
